# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(317, 607)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100% - 10px)cener;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 290, 591))
        self.widget.setObjectName("widget")

        self.mail = QtWidgets.QLineEdit(self.widget)
        self.mail.setGeometry(QtCore.QRect(20, 240, 250, 30))
        self.mail.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                "border:1px solid rgba(0,0,0,0);\n"
                                "border-bottom-color:rgba(46,82,101,255);\n"
                                "color:rgba(255,255,255);\n"
                                "padding-bottom:7px\n"
                                "")
        self.mail.setObjectName("mail")

        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setGeometry(QtCore.QRect(20, 280, 250, 30))
        self.username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgba(255,255,255);\n"
"padding-bottom:7px\n"
"")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(20, 320, 250, 30))
        self.password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgba(255,255,255);\n"
"padding-bottom:7px\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")

        self.verifypass = QtWidgets.QLineEdit(self.widget)
        self.verifypass.setGeometry(QtCore.QRect(20, 360, 250, 30))
        self.verifypass.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                      "border:1px solid rgba(0,0,0,0);\n"
                                      "border-bottom-color:rgba(46,82,101,255);\n"
                                      "color:rgba(255,255,255);\n"
                                      "padding-bottom:7px\n"
                                      "")
        self.verifypass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verifypass.setObjectName("verifypass")

        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(20, 440, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setAutoDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 20, 180, 150))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(70)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(0,125,236,255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 290, 591))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(16,30,41,240);\n"
"border-radius:10px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")

        self.label.raise_()
        self.mail.raise_()
        self.username.raise_()
        self.password.raise_()
        self.verifypass.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mail.setPlaceholderText(_translate("MainWindow", "EMAİL"))
        self.username.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.verifypass.setPlaceholderText(_translate("MainWindow", "VERİFY PASSWORD"))
        self.pushButton.setText(_translate("MainWindow", "R e g i s t e r"))
        self.label_2.setText(_translate("MainWindow", ""))

